[package]
name = "y1337-keymap"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
dirs = "5.0.1"
thiserror = "1.0.56"
