[package]
name = "yeet"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yeet-frontend = { path = "../yeet-frontend" }
tokio = { version = "1.38.1", features = ["full"] }
thiserror = "1.0.61"
clap = "4.5.8"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
dirs = "5.0.1"
