[package]
name = "yeet-keymap"
version = "0.0.1"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
dirs = "5.0.1"
regex = "1.10.4"
thiserror = "1.0.61"
tracing = "0.1.40"
yeet-buffer = { version = "0.0.1", path = "../yeet-buffer" }
