[workspace]
resolver = "2"

members = [
    "yeet", "yeet-buffer", "yeet-frontend", "yeet-keymap",
]

[workspace.package]
authors = ["Alexander Serowy"]
description = "yet another... tui file manager with a touch of neovim like buffers and modal editing"
edition = "2021"
repository = "https://github.com/aserowy/yeet"
version = "0.1.0"

[workspace.dependencies]
ansi-to-tui = "6.0.0"
arboard = { version = "3.4.0", default-features = false, features = ["windows-sys", "wayland-data-control"] }
clap = "4.5.17"
crossterm = { version = "0.28.1", features = ["event-stream"] }
csv = "1.3.0"
dirs = "5.0.1"
flate2 = "1.0.33"
futures = "0.3.30"
infer = "0.16.0"
notify = { version = "6.1.1", default-features = false, features = ["macos_fsevent"] }
pathdiff = "0.2.0"
ratatui = "0.28.1"
regex = "1.10.6"
syntect = { version = "5.2.0", default-features = false, features = ["default-fancy"]}
tar = "0.4.41"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"

[workspace.lints.rust]
unsafe_code = "forbid"
