[package]
name = "yeet-frontend"
version = "0.0.1"
edition = "2021"

[dependencies]
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3.30"
ratatui = "0.27.0"
yeet-keymap = { path = "../yeet-keymap" }
tokio = { version = "1.39.2", features = ["full"] }
csv = "1.3.0"
thiserror = "1.0.61"
notify = { version = "6.1.1", default-features = false, features = ["macos_fsevent"] }
infer = "0.16.0"
dirs = "5.0.1"
pathdiff = "0.2.0"
flate2 = "1.0.30"
tar = "0.4.41"
tracing = "0.1.40"
yeet-buffer = { version = "0.0.1", path = "../yeet-buffer" }
arboard = { version = "3.4.0", default-features = false, features = ["windows-sys", "wayland-data-control"] }
