[package]
name = "yeet-frontend"
version = "0.0.1"
edition = "2021"

[dependencies]
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3.30"
ratatui = "0.26.1"
yeet-keymap = { path = "../yeet-keymap" }
tokio = { version = "1.35.1", features = ["full"] }
csv = "1.3.0"
thiserror = "1.0.56"
notify = { version = "6.1.1", default-features = false, features = ["macos_fsevent"] }
infer = "0.15.0"
dirs = "5.0.1"
pathdiff = "0.2.0"
flate2 = "1.0.28"
tar = "0.4.40"
