[package]
name = "yeet-buffer"

authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
ansi-to-tui.workspace = true
ratatui.workspace = true
tracing.workspace = true
