[package]
name = "teywi"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teywi-frontend = { path = "../teywi-frontend" }
tokio = { version = "1.35.1", features = ["full"] }
